from cListaEstatica import *


def main():
    lista = listaEstatica(5)
    print("\n***Instanciei um objeto da classe lista estática***")
    print("\n-----------------------------------------------------------\n")
    print("Mostrando lista na tela...\n")
    print("Lista:", lista.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    lista.insereValor(11)
    lista.insereValor(3)
    lista.insereValor(8)
    print("Inseri os valores 11, 3 e 8.\n")
    print("Lista:", lista.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    lista.insereValor(5, 1)
    lista.insereValor(2, 3)
    print("Inseri os números 5 e 4 na 2ª e na 4ª posição, respectivamente.\n")
    print("Lista:", lista.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Imprimindo em ordem crescente...\n")
    print("Lista:", lista.imprimeCrescente(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Imprimindo em ordem decrescente...\n")
    print("Lista:", lista.imprimeDecrescente(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Inserindo o valor 6 na lista...\n")
    lista.insereValor(6)
    print("Lista:", lista.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Criando uma cópia da minha lista...\n")
    copiaDaLista = lista.copia()
    print("Lista:", lista.imprime(), sep=' ')
    print("\nCópia:", copiaDaLista.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Instanciando outra lista estática...\n")
    outraLista = listaEstatica(4)
    print("Inserindo valores 1, 9, 2 e 4...\n")
    outraLista.insereValor(1)
    outraLista.insereValor(9)
    outraLista.insereValor(2)
    outraLista.insereValor(4)
    print("Outra lista:", outraLista.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Concatenando as duas listas estáticas...\n")
    listasConcatenadas = lista.concatena(outraLista)
    print("Lista concatenada:", listasConcatenadas.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Removendo ocorrências do número 2...\n")
    listasConcatenadas.removeOcorrencias(2)
    print("Lista concatenada:", listasConcatenadas.imprime(), sep=' ')
    print("\n-----------------------------------------------------------\n")
    print("Procurando posição do número 8...\n")
    print(f"O número 8 ocupa o índice {listasConcatenadas.encontraIndice(8)}.")
    print("\n-----------------------------------------------------------\n")
    print("Procurando elemento na posição 5...\n")
    print(f"O elemento {listasConcatenadas.encontraElemento(5)} ocupa o índice 5.")
    print("\n-----------------------------------------------------------\n")
    
    
if __name__ == '__main__':
    main()
    
